packages:
- category: Browser
  description: ''
  id: Google.Chrome
  name: Google Chrome
- category: Browser
  description: ''
  id: Brave.Brave
  name: Brave
- category: Browser
  description: ''
  id: Mozilla.Firefox
  name: Mozilla Firefox
- category: Browser
  description: ''
  id: Microsoft.Edge
  name: Microsoft Edge
- category: Communication
  description: ''
  id: 9NKSQGP7F2NH
  name: WhatsApp
- category: Communication
  description: ''
  id: Discord.Discord
  name: Discord
- category: Communication
  description: ''
  id: Proton.ProtonMail
  name: Proton Mail
- category: Security & Privacy
  description: ''
  id: Proton.ProtonPass
  name: Proton Pass
- category: Security & Privacy
  description: ''
  id: Proton.ProtonVPN
  name: Proton VPN
- category: Security & Privacy
  description: ''
  id: Cloudflare.Warp
  name: Cloudflare Warp
