packages:
  # Browsers
  - id: Google.Chrome
    name: Google Chrome
    description: "Fast and secure web browser by Google"
    category: Browsers
  
  - id: Brave.Brave
    name: Brave
    description: "Privacy-focused browser with built-in ad blocking"
    category: Browsers
  
  - id: Mozilla.Firefox
    name: Mozilla Firefox
    description: "Open-source web browser focused on privacy"
    category: Browsers
  
  - id: Microsoft.Edge
    name: Microsoft Edge
    description: "Modern web browser built on Chromium"
    category: Browsers

  # Communication
  - id: 9NKSQGP7F2NH
    name: WhatsApp
    description: "Messaging and voice/video call application"
    category: Communication
  
  - id: Discord.Discord
    name: Discord
    description: "Voice, video, and text chat for communities and gamers"
    category: Communication
  
  - id: Proton.ProtonMail
    name: Proton Mail
    description: "Encrypted email service with privacy focus"
    category: Communication

  # Security & Privacy
  - id: Proton.ProtonPass
    name: Proton Pass
    description: "End-to-end encrypted password manager"
    category: Security & Privacy
  
  - id: Proton.ProtonVPN
    name: Proton VPN
    description: "Secure VPN service with no-logs policy"
    category: Security & Privacy
  
  - id: Cloudflare.Warp
    name: Cloudflare Warp
    description: "Free VPN and DNS service by Cloudflare"
    category: Security & Privacy

  # Cloud Storage
  - id: Proton.ProtonDrive
    name: Proton Drive
    description: "Encrypted cloud storage service"
    category: Cloud Storage
  
  - id: ente-io.photos-desktop
    name: Ente Photos
    description: "End-to-end encrypted photo backup and storage"
    category: Cloud Storage

  # Gaming
  - id: Valve.Steam
    name: Steam
    description: "Digital distribution platform for PC games"
    category: Gaming
  
  - id: ElectronicArts.EADesktop
    name: EA Desktop
    description: "Electronic Arts game launcher and store"
    category: Gaming
  
  - id: Ubisoft.Connect
    name: Ubisoft Connect
    description: "Ubisoft's game launcher and rewards platform"
    category: Gaming
  
  - id: ParadoxInteractive.ParadoxLauncher
    name: Paradox Launcher
    description: "Game launcher for Paradox Interactive titles"
    category: Gaming
  
  - id: NexusMods.Vortex
    name: Vortex
    description: "Mod manager for games from Nexus Mods"
    category: Gaming
  
  - id: Blizzard.BattleNet
    name: Battle.net
    description: "Blizzard's game launcher for WoW, Overwatch, and more"
    category: Gaming
  
  - id: Parsec.Parsec
    name: Parsec
    description: "Low-latency game streaming and remote desktop"
    category: Gaming

  # Development
  - id: Microsoft.VisualStudioCode
    name: Visual Studio Code
    description: "Powerful code editor with extensions support"
    category: Development
  
  - id: 9MSVKQC78PK6
    name: Debian (WSL)
    description: "Debian Linux distribution for Windows Subsystem for Linux"
    category: Development
  
  - id: Python.Launcher
    name: Python Launcher
    description: "Launcher for Python versions on Windows"
    category: Development
  
  - id: Python.Python.3.9
    name: Python 3.9
    description: "Python programming language version 3.9"
    category: Development
  
  - id: Oracle.JavaRuntimeEnvironment
    name: Java Runtime Environment
    description: "Java runtime required for Java applications"
    category: Development
  
  - id: OpenJS.NodeJS
    name: Node.js
    description: "JavaScript runtime built on Chrome's V8 engine"
    category: Development
  
  - id: Microsoft.WindowsTerminal
    name: Windows Terminal
    description: "Modern terminal application for Windows"
    category: Development
  
  - id: Git.Git
    name: Git
    description: "Distributed version control system"
    category: Development
  
  - id: Microsoft.PowerShell
    name: PowerShell
    description: "Cross-platform task automation and configuration tool"
    category: Development
  
  - id: JanDeDobbeleer.OhMyPosh
    name: Oh My Posh
    description: "Prompt theme engine for any shell"
    category: Development
  
  - id: Anthropic.Claude
    name: Claude
    description: "AI assistant by Anthropic for desktop"
    category: Development
  
  - id: Ollama.Ollama
    name: Ollama
    description: "Run large language models locally"
    category: Development

  # Productivity
  - id: TheDocumentFoundation.LibreOffice
    name: LibreOffice
    description: "Free and open-source office suite"
    category: Productivity
  
  - id: PDFgear.PDFgear
    name: PDFgear
    description: "Free PDF reader and editor"
    category: Productivity
  
  - id: Notepad++.Notepad++
    name: Notepad++
    description: "Advanced text and source code editor"
    category: Productivity
  
  - id: Obsidian.Obsidian
    name: Obsidian
    description: "Powerful knowledge base and note-taking app"
    category: Productivity

  # Media & Entertainment
  - id: VideoLAN.VLC
    name: VLC Media Player
    description: "Free and open-source multimedia player"
    category: Media & Entertainment
  
  - id: OBSProject.OBSStudio
    name: OBS Studio
    description: "Free software for video recording and live streaming"
    category: Media & Entertainment
  
  - id: Spotify.Spotify
    name: Spotify
    description: "Digital music streaming service"
    category: Media & Entertainment
  
  - id: 9NMS233VM4Z9
    name: Amazon Music
    description: "Music streaming service by Amazon"
    category: Media & Entertainment
  
  - id: Audacity.Audacity
    name: Audacity
    description: "Free and open-source audio editor"
    category: Media & Entertainment
  
  - id: HandBrake.HandBrake
    name: HandBrake
    description: "Open-source video transcoder"
    category: Media & Entertainment

  # Creative Tools
  - id: GIMP.GIMP.3
    name: GIMP
    description: "Free and open-source image editor"
    category: Creative Tools
  
  - id: BlenderFoundation.Blender
    name: Blender
    description: "Free 3D creation suite for modeling, animation, and rendering"
    category: Creative Tools
  
  - id: Upscayl.Upscayl
    name: Upscayl
    description: "AI-powered image upscaling tool"
    category: Creative Tools

  # File Management
  - id: 7zip.7zip
    name: 7-Zip
    description: "Free and open-source file archiver"
    category: File Management
  
  - id: M2Team.NanaZip
    name: NanaZip
    description: "Modern file archiver based on 7-Zip"
    category: File Management
  
  - id: RARLab.WinRAR
    name: WinRAR
    description: "Archive manager for RAR and ZIP files"
    category: File Management
  
  - id: qBittorrent.qBittorrent
    name: qBittorrent
    description: "Free and open-source BitTorrent client"
    category: File Management
  
  - id: SoftDeluxe.FreeDownloadManager
    name: Free Download Manager
    description: "Download accelerator and manager"
    category: File Management
  
  - id: AdrienAllard.FileConverter
    name: File Converter
    description: "Convert and compress files in Windows Explorer"
    category: File Management

  # System Monitoring
  - id: ALCPU.CoreTemp
    name: Core Temp
    description: "CPU temperature monitoring tool"
    category: System Monitoring
  
  - id: CPUID.HWMonitor
    name: HWMonitor
    description: "Hardware monitoring tool for voltages, temperatures, and fans"
    category: System Monitoring
  
  - id: CPUID.CPU-Z
    name: CPU-Z
    description: "System information tool for CPU, motherboard, and memory"
    category: System Monitoring
  
  - id: TechPowerUp.GPU-Z
    name: GPU-Z
    description: "Graphics card information and monitoring utility"
    category: System Monitoring
  
  - id: CrystalDewWorld.CrystalDiskInfo
    name: CrystalDiskInfo
    description: "Hard disk health monitoring tool"
    category: System Monitoring

  # System Tools
  - id: 9P8LTPGCBZXD
    name: Wintoys
    description: "Modern Windows utilities and tweaks tool"
    category: System Tools
  
  - id: MartiCliment.UniGetUI
    name: UniGetUI
    description: "Unified interface for multiple package managers"
    category: System Tools
  
  - id: Chocolatey.Chocolatey
    name: Chocolatey
    description: "Package manager for Windows"
    category: System Tools
  
  - id: Eassos.DiskGenius
    name: DiskGenius
    description: "Partition manager and data recovery tool"
    category: System Tools
  
  - id: MiniTool.PartitionWizard.Free
    name: MiniTool Partition Wizard
    description: "Free partition manager and disk management tool"
    category: System Tools
  
  - id: IObit.IObitUnlocker
    name: IObit Unlocker
    description: "Unlock and delete stubborn files and folders"
    category: System Tools

  # Customization
  - id: 9PF4KZ2VN4W9
    name: TranslucentTB
    description: "Make Windows taskbar transparent or translucent"
    category: Customization
  
  - id: Nilesoft.Shell
    name: Nilesoft Shell
    description: "Powerful context menu manager for Windows"
    category: Customization
  
  - id: StartIsBack.StartAllBack
    name: StartAllBack
    description: "Restore classic Windows UI elements"
    category: Customization
  
  - id: FxSound.FxSound
    name: FxSound
    description: "Audio enhancement and equalizer for Windows"
    category: Customization

  # Hardware & Drivers
  - id: Corsair.iCUE.5
    name: Corsair iCUE
    description: "Control software for Corsair peripherals and components"
    category: Hardware & Drivers
  
  - id: Logitech.OptionsPlus
    name: Logitech Options+
    description: "Customize Logitech mice, keyboards, and touchpads"
    category: Hardware & Drivers
  
  - id: Logitech.GHUB
    name: Logitech G HUB
    description: "Gaming software for Logitech gaming devices"
    category: Hardware & Drivers
  
  - id: Logitech.LogiTune
    name: Logi Tune
    description: "Customize Logitech webcams and headsets"
    category: Hardware & Drivers
  
  - id: Wacom.WacomTabletDriver
    name: Wacom Tablet Driver
    description: "Driver software for Wacom drawing tablets"
    category: Hardware & Drivers
  
  - id: Nvidia.PhysX
    name: NVIDIA PhysX
    description: "Physics engine runtime for gaming"
    category: Hardware & Drivers

  # Utilities
  - id: Starpine.Screenbox
    name: Screenbox
    description: "Modern media player for Windows"
    category: Utilities
  
  - id: 9N7JSXC1SJK6
    name: Blip Transfer
    description: "Fast file transfer between devices"
    category: Utilities
  
  - id: 9WZDNCRFJ3PR
    name: Windows Clock
    description: "Clock app with alarm, timer, and stopwatch"
    category: Utilities
  
  - id: 9WZDNCRFJBBG
    name: Windows Voice Recorder
    description: "Simple audio recording app for Windows"
    category: Utilities
  
  - id: Nickvision.Parabolic
    name: Parabolic
    description: "Download videos and audio from online platforms"
    category: Utilities
  
  - id: LocalSend.LocalSend
    name: LocalSend
    description: "Share files to nearby devices without internet"
    category: Utilities
  
  - id: Famatech.RadminVPN
    name: Radmin VPN
    description: "Free VPN for gaming and remote access"
    category: Utilities

  # System Dependencies
  - id: Microsoft.AppInstaller
    name: App Installer
    description: "Install apps from MSIX packages"
    category: System Dependencies
  
  - id: Microsoft.DotNet.DesktopRuntime.6
    name: .NET Desktop Runtime 6
    description: "Runtime for .NET 6 desktop applications"
    category: System Dependencies
  
  - id: Microsoft.DotNet.DesktopRuntime.8
    name: .NET Desktop Runtime 8
    description: "Runtime for .NET 8 desktop applications"
    category: System Dependencies
  
  - id: Microsoft.ServerSpeechPlatformRuntime
    name: Server Speech Platform Runtime
    description: "Runtime for speech recognition applications"
    category: System Dependencies
  
  - id: Microsoft.VCLibs.Desktop.14
    name: VC Libs Desktop 14
    description: "Visual C++ library dependencies"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2005.x86
    name: VC++ 2005 Redistributable x86
    description: "Visual C++ 2005 runtime components (32-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2008.x64
    name: VC++ 2008 Redistributable x64
    description: "Visual C++ 2008 runtime components (64-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2008.x86
    name: VC++ 2008 Redistributable x86
    description: "Visual C++ 2008 runtime components (32-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2010.x64
    name: VC++ 2010 Redistributable x64
    description: "Visual C++ 2010 runtime components (64-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2010.x86
    name: VC++ 2010 Redistributable x86
    description: "Visual C++ 2010 runtime components (32-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2012.x64
    name: VC++ 2012 Redistributable x64
    description: "Visual C++ 2012 runtime components (64-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2012.x86
    name: VC++ 2012 Redistributable x86
    description: "Visual C++ 2012 runtime components (32-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2013.x64
    name: VC++ 2013 Redistributable x64
    description: "Visual C++ 2013 runtime components (64-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2013.x86
    name: VC++ 2013 Redistributable x86
    description: "Visual C++ 2013 runtime components (32-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2015+.x64
    name: VC++ 2015-2022 Redistributable x64
    description: "Visual C++ 2015-2022 runtime components (64-bit)"
    category: System Dependencies
  
  - id: Microsoft.VCRedist.2015+.x86
    name: VC++ 2015-2022 Redistributable x86
    description: "Visual C++ 2015-2022 runtime components (32-bit)"
    category: System Dependencies
  
  - id: Microsoft.VSTOR
    name: Visual Studio Tools for Office Runtime
    description: "Runtime for Office add-ins and solutions"
    category: System Dependencies